apiVersion: v1
kind: Pod
metadata:
  annotations:
    task_id: test
    dag_id: k8s_knaudit_example
    run_id: manual__2023-05-03T11:00:00+00:00
  name: knaudit
spec:
  initContainers:
  - args:
    - navikt/nada-dags
    - main
    - /dags
    - "60"
    command:
    - /bin/sh
    - /git-clone.sh
    image: europe-west1-docker.pkg.dev/knada-gcp/knada/git-sync:2023-03-09-bfc0f3e
    name: git-clone
    volumeMounts:
    - mountPath: /dags
      name: dags-data
    - mountPath: /keys
      name: github-app-secret
  containers:
  - name: knaudit
    env:
    - name: NAMESPACE
      valueFrom :
        fieldRef :
          fieldPath : metadata.namespace
    - name: ELASTICSEARCH_URL
      value: https://log-ingest.adeo.no
    - name: ELASTICSEARCH_INDEX
      value: tjenestekall-knada-airflow-run-audit
    - name: CA_CERT_PATH
      value: /etc/pki/tls/certs/ca-bundle.crt
    - name: GIT_REPO_PATH
      value: /dags
    - name: AIRFLOW_DAG_ID
      valueFrom :
        fieldRef :
          fieldPath : metadata.annotations['dag_id']
    - name: AIRFLOW_RUN_ID
      valueFrom :
        fieldRef :
          fieldPath : metadata.annotations['run_id']
    - name: AIRFLOW_TASK_ID
      valueFrom :
        fieldRef :
          fieldPath : metadata.annotations['task_id']
    - name: AIRFLOW_DB_URL
      valueFrom:
        secretKeyRef:
          name: airflow-db
          key: connection
    image: europe-west1-docker.pkg.dev/knada-gcp/knada/knaudit:2023-03-13-2cc53c1
    imagePullPolicy: Always
    volumeMounts:
    - mountPath: /dags
      name: dags-data
    - mountPath: /etc/pki/tls/certs/ca-bundle.crt
      name: ca-bundle-pem
      readOnly: true
      subPath: ca-bundle.pem
  securityContext:
    fsGroup: 0
    runAsUser: 50000
    runAsNonRoot: true
  volumes:
  - emptyDir: {}
    name: dags-data
  - name: github-app-secret
    secret:
      defaultMode: 448
      secretName: github-app-secret
  - configMap:
      defaultMode: 420
      name: ca-bundle-pem
    name: ca-bundle-pem
